Elaborado por Fabian Niño

In [10]:
#Crear arreglo normal
ejemplo=["hola",1,"mundo",2]
ejemplo[0:2]

['hola', 1]

In [12]:
#crear e imprimir numpy array
import numpy as np
ejm=np.array(["numpy",1,"ejemplos",2])
ejm[0:2]

array(['numpy', '1'], dtype='<U11')

In [14]:
#Imprimirmos la versión del Numpy
print(np.__version__)

1.20.3


In [15]:
#type
type(np)

module

In [21]:
np.dtype

numpy.dtype

In [22]:
ejm

array(['numpy', '1', 'ejemplos', '2'], dtype='<U11')

In [27]:
#Reemplazar
ejm[0:2]="hola","mundo"
ejm

array(['hola', 'mundo', 'ejemplos', '2'], dtype='<U11')

In [28]:
ejm.shape

(4,)

In [29]:
ejm.ndim

1

In [30]:
ejm.size

4

In [35]:
ejm.mean

<function ndarray.mean>

In [36]:
ejm.max

<function ndarray.max>

In [38]:
arr=np.array([1,6,8,35,3])
arr

array([ 1,  6,  8, 35,  3])

In [40]:
arr.max()

35

In [41]:
arr.min()

1

In [44]:
arr2=np.array([45,76,34556,345,643])
arr2

array([   45,    76, 34556,   345,   643])

In [46]:
#Suma de matrices
arrsum=arr+arr2
arrsum

array([   46,    82, 34564,   380,   646])

In [47]:
#Resta de matrices
arrsum=arr*2-arr2
arrsum

array([   -43,    -64, -34540,   -275,   -637])

In [49]:
add=np.add(arr,arr2)
add

array([   46,    82, 34564,   380,   646])

In [54]:
subtract=np.subtract(arr,arr2)
print(subtract)

[   -44    -70 -34548   -310   -640]


In [55]:
multiplicacion=arr*arr2
multiplicacion

array([    45,    456, 276448,  12075,   1929])

In [56]:
x=np.dot(arr,arr2)
x

290953

In [57]:
arr

array([ 1,  6,  8, 35,  3])

In [59]:
arr3=arr+10
arr3

array([11, 16, 18, 45, 13])

In [61]:
np.pi

3.141592653589793

In [62]:
np.sin(arr)

array([ 0.84147098, -0.2794155 ,  0.98935825, -0.42818267,  0.14112001])

In [63]:
np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])